### ISSUE TITLE
Your demos don't work.

### ISSUE THREAD

**Issue by retzion** [Aymkdn/picoModal-Accessible#1]
Would be nice to see an example working. http://aymkdn.github.io/picoModal-Accessible/#

**Comment by Aymkdn** [comment]
I've just tried, and everything works as expected.

Which browser do you use? Do you block javascript?

**Comment by retzion** [comment]
I tried Firefox, Chrome, and Safari (all with javascript enabled). All I got when clicking the demo links was a smooth scroll to the top of the page (due to the # hash href) and an unresolved request to github-proxy.kodono.info which seems to eventually timeout.

**Comment by Aymkdn** [comment]
So if you go to http://github-proxy.kodono.info/?q=https://raw.githubusercontent.com/Aymkdn/picoModal-Accessible/master/picoModal.js you don't see the JS file ?

**Comment by Aymkdn** [comment]
I moved the ghpages to /docs and I've locally moved the picoModal.js.
